/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { metadataRulesListMetadataRules } from "../../funcs/metadataRulesListMetadataRules.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.ListMetadataRulesRequest$inboundSchema,
};

export const tool$metadataRulesListMetadataRules: ToolDefinition<typeof args> =
  {
    name: "list-metadata-rules",
    description:
      `Retrieves a list of all conditional metadata rules defined in your accountcloudinary

Retrieves a list of all metadata rules in the cloud.`,
    scopes: ["builder"],
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] = await metadataRulesListMetadataRules(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
