/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { metadataRulesUpdateMetadataRule } from "../../funcs/metadataRulesUpdateMetadataRule.js";
import * as components from "../../models/components/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  externalId: z.string(),
  metadataRuleUpdate: components.MetadataRuleUpdate$inboundSchema,
};

export const tool$metadataRulesUpdateMetadataRule: ToolDefinition<typeof args> =
  {
    name: "update-metadata-rule",
    description: `Updates an existing conditional metadata rule's definition

Updates the properties and configuration of an existing metadata rule.`,
    scopes: ["builder"],
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] = await metadataRulesUpdateMetadataRule(
        client,
        args.externalId,
        args.metadataRuleUpdate,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
