/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { CloudinarySMDCore } from "../core.js";
import { encodeFormQuery, encodeJSON, encodeSimple } from "../lib/encodings.js";
import * as M from "../lib/matchers.js";
import { compactMap } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { RequestOptions } from "../lib/sdks.js";
import { extractSecurity, resolveGlobalSecurity } from "../lib/security.js";
import { pathToFunc } from "../lib/url.js";
import * as components from "../models/components/index.js";
import { CloudinarySMDError } from "../models/errors/cloudinarysmderror.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import * as errors from "../models/errors/index.js";
import { ResponseValidationError } from "../models/errors/responsevalidationerror.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import * as operations from "../models/operations/index.js";
import { APICall, APIPromise } from "../types/async.js";
import { Result } from "../types/fp.js";

/**
 * Search datasource values in a metadata field
 *
 * @remarks
 * Performs a search within a specific metadata field's datasource to find matching values, with support for exact or partial matches.
 */
export function metadataFieldsSearchDatasourceInMDField(
  client: CloudinarySMDCore,
  externalId: string,
  requestBody: operations.SearchDatasourceInMDFieldRequestBody,
  maxResults?: number | undefined,
  term?: string | undefined,
  exactMatch?: boolean | undefined,
  options?: RequestOptions,
): APIPromise<
  Result<
    components.MetadataFieldDatasourceValuesArray,
    | errors.ApiError
    | CloudinarySMDError
    | ResponseValidationError
    | ConnectionError
    | RequestAbortedError
    | RequestTimeoutError
    | InvalidRequestError
    | UnexpectedClientError
    | SDKValidationError
  >
> {
  return new APIPromise($do(
    client,
    externalId,
    requestBody,
    maxResults,
    term,
    exactMatch,
    options,
  ));
}

async function $do(
  client: CloudinarySMDCore,
  externalId: string,
  requestBody: operations.SearchDatasourceInMDFieldRequestBody,
  maxResults?: number | undefined,
  term?: string | undefined,
  exactMatch?: boolean | undefined,
  options?: RequestOptions,
): Promise<
  [
    Result<
      components.MetadataFieldDatasourceValuesArray,
      | errors.ApiError
      | CloudinarySMDError
      | ResponseValidationError
      | ConnectionError
      | RequestAbortedError
      | RequestTimeoutError
      | InvalidRequestError
      | UnexpectedClientError
      | SDKValidationError
    >,
    APICall,
  ]
> {
  const input: operations.SearchDatasourceInMDFieldRequest = {
    externalId: externalId,
    requestBody: requestBody,
    maxResults: maxResults,
    term: term,
    exactMatch: exactMatch,
  };

  const parsed = safeParse(
    input,
    (value) =>
      operations.SearchDatasourceInMDFieldRequest$outboundSchema.parse(value),
    "Input validation failed",
  );
  if (!parsed.ok) {
    return [parsed, { status: "invalid" }];
  }
  const payload = parsed.value;
  const body = encodeJSON("body", payload.RequestBody, { explode: true });

  const pathParams = {
    cloud_name: encodeSimple("cloud_name", client._options.cloudName, {
      explode: false,
      charEncoding: "percent",
    }),
    external_id: encodeSimple("external_id", payload.external_id, {
      explode: false,
      charEncoding: "percent",
    }),
  };

  const path = pathToFunc(
    "/v1_1/{cloud_name}/metadata_fields/{external_id}/datasource/search",
  )(pathParams);

  const query = encodeFormQuery({
    "exact_match": payload.exact_match,
    "max_results": payload.max_results,
    "term": payload.term,
  });

  const headers = new Headers(compactMap({
    "Content-Type": "application/json",
    Accept: "application/json",
  }));

  const securityInput = await extractSecurity(client._options.security);
  const requestSecurity = resolveGlobalSecurity(securityInput);

  const context = {
    options: client._options,
    baseURL: options?.serverURL ?? client._baseURL ?? "",
    operationID: "searchDatasourceInMDField",
    oAuth2Scopes: [],

    resolvedSecurity: requestSecurity,

    securitySource: client._options.security,
    retryConfig: options?.retries
      || client._options.retryConfig
      || { strategy: "none" },
    retryCodes: options?.retryCodes || ["429", "500", "502", "503", "504"],
  };

  const requestRes = client._createRequest(context, {
    security: requestSecurity,
    method: "POST",
    baseURL: options?.serverURL,
    path: path,
    headers: headers,
    query: query,
    body: body,
    userAgent: client._options.userAgent,
    timeoutMs: options?.timeoutMs || client._options.timeoutMs || -1,
  }, options);
  if (!requestRes.ok) {
    return [requestRes, { status: "invalid" }];
  }
  const req = requestRes.value;

  const doResult = await client._do(req, {
    context,
    errorCodes: ["401", "404", "4XX", "5XX"],
    retryConfig: context.retryConfig,
    retryCodes: context.retryCodes,
  });
  if (!doResult.ok) {
    return [doResult, { status: "request-error", request: req }];
  }
  const response = doResult.value;

  const responseFields = {
    HttpMeta: { Response: response, Request: req },
  };

  const [result] = await M.match<
    components.MetadataFieldDatasourceValuesArray,
    | errors.ApiError
    | CloudinarySMDError
    | ResponseValidationError
    | ConnectionError
    | RequestAbortedError
    | RequestTimeoutError
    | InvalidRequestError
    | UnexpectedClientError
    | SDKValidationError
  >(
    M.json(200, components.MetadataFieldDatasourceValuesArray$inboundSchema),
    M.jsonErr([401, 404], errors.ApiError$inboundSchema),
    M.fail("4XX"),
    M.fail("5XX"),
  )(response, req, { extraFields: responseFields });
  if (!result.ok) {
    return [result, { status: "complete", request: req, response }];
  }

  return [result, { status: "complete", request: req, response }];
}
