/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { metadataRulesCreateMetadataRule } from "../funcs/metadataRulesCreateMetadataRule.js";
import { metadataRulesDeleteMetadataRule } from "../funcs/metadataRulesDeleteMetadataRule.js";
import { metadataRulesListMetadataRules } from "../funcs/metadataRulesListMetadataRules.js";
import { metadataRulesUpdateMetadataRule } from "../funcs/metadataRulesUpdateMetadataRule.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class MetadataRules extends ClientSDK {
  /**
   * Creates a new conditional metadata rule
   *
   * @remarks
   * Creates a new metadata rule with the specified properties and configuration.
   */
  async createMetadataRule(
    request: components.MetadataRuleCreate,
    options?: RequestOptions,
  ): Promise<components.MetadataRuleResponse> {
    return unwrapAsync(metadataRulesCreateMetadataRule(
      this,
      request,
      options,
    ));
  }

  /**
   * Retrieves a list of all conditional metadata rules defined in your accountcloudinary
   *
   * @remarks
   * Retrieves a list of all metadata rules in the cloud.
   */
  async listMetadataRules(
    request: operations.ListMetadataRulesRequest,
    options?: RequestOptions,
  ): Promise<operations.ListMetadataRulesResponse> {
    return unwrapAsync(metadataRulesListMetadataRules(
      this,
      request,
      options,
    ));
  }

  /**
   * Updates an existing conditional metadata rule's definition
   *
   * @remarks
   * Updates the properties and configuration of an existing metadata rule.
   */
  async updateMetadataRule(
    externalId: string,
    metadataRuleUpdate: components.MetadataRuleUpdate,
    options?: RequestOptions,
  ): Promise<components.MetadataRuleResponse> {
    return unwrapAsync(metadataRulesUpdateMetadataRule(
      this,
      externalId,
      metadataRuleUpdate,
      options,
    ));
  }

  /**
   * Deletes a conditional metadata rule by its ID
   *
   * @remarks
   * Permanently deletes a metadata rule.
   */
  async deleteMetadataRule(
    externalId: string,
    options?: RequestOptions,
  ): Promise<operations.DeleteMetadataRuleResponse> {
    return unwrapAsync(metadataRulesDeleteMetadataRule(
      this,
      externalId,
      options,
    ));
  }
}
