/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { MetadataFields } from "./metadatafields.js";
import { MetadataRules } from "./metadatarules.js";

export class CloudinarySMD extends ClientSDK {
  private _metadataFields?: MetadataFields;
  get metadataFields(): MetadataFields {
    return (this._metadataFields ??= new MetadataFields(this._options));
  }

  private _metadataRules?: MetadataRules;
  get metadataRules(): MetadataRules {
    return (this._metadataRules ??= new MetadataRules(this._options));
  }
}
