/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CreateMetadataFieldGlobals = {
  /**
   * The cloud name of your product environment.
   */
  cloudName?: string | undefined;
};

/** @internal */
export const CreateMetadataFieldGlobals$inboundSchema: z.ZodType<
  CreateMetadataFieldGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  cloud_name: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "cloud_name": "cloudName",
  });
});

/** @internal */
export type CreateMetadataFieldGlobals$Outbound = {
  cloud_name?: string | undefined;
};

/** @internal */
export const CreateMetadataFieldGlobals$outboundSchema: z.ZodType<
  CreateMetadataFieldGlobals$Outbound,
  z.ZodTypeDef,
  CreateMetadataFieldGlobals
> = z.object({
  cloudName: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    cloudName: "cloud_name",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateMetadataFieldGlobals$ {
  /** @deprecated use `CreateMetadataFieldGlobals$inboundSchema` instead. */
  export const inboundSchema = CreateMetadataFieldGlobals$inboundSchema;
  /** @deprecated use `CreateMetadataFieldGlobals$outboundSchema` instead. */
  export const outboundSchema = CreateMetadataFieldGlobals$outboundSchema;
  /** @deprecated use `CreateMetadataFieldGlobals$Outbound` instead. */
  export type Outbound = CreateMetadataFieldGlobals$Outbound;
}

export function createMetadataFieldGlobalsToJSON(
  createMetadataFieldGlobals: CreateMetadataFieldGlobals,
): string {
  return JSON.stringify(
    CreateMetadataFieldGlobals$outboundSchema.parse(createMetadataFieldGlobals),
  );
}

export function createMetadataFieldGlobalsFromJSON(
  jsonString: string,
): SafeParseResult<CreateMetadataFieldGlobals, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateMetadataFieldGlobals$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateMetadataFieldGlobals' from JSON`,
  );
}
