name: Build and Push Docker Image

on:
  workflow_run:
    workflows: ["Publish"]
    types:
      - completed

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: cloudinary/structured-metadata-mcp

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Extract short SHA
        id: sha
        run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Set up QEMU (for multi-arch)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ${{ env.IMAGE_NAME }}:${{ github.event_name == 'release' && github.event.release.tag_name || steps.sha.outputs.sha }}
            ${{ env.IMAGE_NAME }}:${{ steps.sha.outputs.sha }}
            ${{ env.IMAGE_NAME }}:latest
